### ISSUE TITLE
Cannot use @Model.xxx to output the string which contains different encoding charactors

### ISSUE THREAD

**Issue by yukozh** [CodeComb/vnextcn.org#12]
It will throw an exception Argument encoder does not implement MaxOutputCharsPerInputChar correctly.

Because these days MS changed the HtmlEncoder. There was a verify method in it. If the string is illegal it will throw this.

@weitzhandler Do you have any suggestions to solve this problem?

:sob: 

The problem occurred with [Show.cshtml](https://github.com/CodeComb/vNextExperimentCenter/blob/dev/src/CodeComb.vNextExperimentCenter/Views/Status/Show.cshtml#L76)

Model.Output mixed `GB2312` and `UTF8`

**Comment by yukozh** [comment]
Changed to ajax load

**Comment by weitzhandler** [comment]
@Kagamine Please do not assign me to issues.

Thanks
